codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
          - dev
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "*/tests/*"
  - "*/test_*.py"
  - "*/__pycache__/*"
  - "*/mock_client.py"
  - "setup.py"
  - "build.py"
